# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('images', models.CharField(max_length=300)),
                ('snippet', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
